In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, Markdown

In [2]:
from utils import profile_column

# Uber 2024 Dataset – Basic Analysis

## Objective
This notebook explores the Uber 2024 booking dataset to:
- Understand data size and structure
- Evaluate data quality
- Analyze field distributions
- Identify logical relationships
- Extract business insights
- Identify potential applications

In [3]:
pd.set_option("display.max_columns", None)
df = pd.read_csv("../data/Database.csv")
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,3/23/2024,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11/29/2024,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,8/23/2024,8:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,10/21/2024,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,9/16/2024,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

## Dataset Size and Explanation
The dataset is of the following size:
- 17 Fields (Columns/Features)
- 150,000 Records (Instances, Samples)

In [4]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 17 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Cancelled Rides by Customer        10500 non-null   float64
 7   Reason for cancelling by Customer  10500 non-null   object
 8   Cancelled Rides by Driver          27000 non-null   float64
 9   Driver Cancellation Reason         27000 non-null   object
 10  Incomplete Rides                   9000 non-null    float64
 11  Incomplete Rides Reason            9000 non-null    object
 12  Booking Value                      102000 non-null  float64
 13  Ride Distance                      102000 non-null  float64
 14  Driver Ratings                     93000 non-null   float64
 15  Customer Rating                    93000 non-null   float64
 16  Payment Method                     102000 non-null  object
dtypes: float64(7), object(10)
memory usage: 88.9 MB

In [5]:
duplicate_count = df.duplicated().sum()
print(f"Total duplicate rows: {duplicate_count:,}")

Total duplicate rows: 0


### Explanation

Based on the output of the `info()` function, we can conclude the following:

* The dataset occupies approximately **90 MB** of memory.
* It contains **Uber car booking transaction records**.
* No duplicate records found.
* Several columns include **null (missing) values**.
* This dataset enables various analyses to better understand the state and performance of **car bookings in 2024**, including trends, cancellations, ride completion rates, revenue patterns, and customer/driver behavior.

## Field-by-Field Analysis
In this section, we will explore each field to get an insight of what they are and what do they represent.

In [6]:
df.dtypes

Date                                  object
Time                                  object
Booking ID                            object
Booking Status                        object
Customer ID                           object
Vehicle Type                          object
Cancelled Rides by Customer          float64
Reason for cancelling by Customer     object
Cancelled Rides by Driver            float64
Driver Cancellation Reason            object
Incomplete Rides                     float64
Incomplete Rides Reason               object
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                        object
dtype: object

In [7]:
cols_profiles = []
for col in df.columns:
    cols_profiles.append(profile_column(df, col))

display(Markdown('\n\n'.join(cols_profiles)))

#### Column Profile: `Date`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `9,892,571 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `365`
- **Duplicate Values:** `149,635`
- **Duplicate Percentage:** `99.76%`

##### Sample Values
`['3/23/2024', '11/29/2024', '8/23/2024', '10/21/2024', '9/16/2024']`



---



#### Column Profile: `Time`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `9,715,865 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `62,910`
- **Duplicate Values:** `87,090`
- **Duplicate Percentage:** `58.06%`

##### Sample Values
`['12:29:38', '18:01:39', '8:56:10', '17:17:25', '22:08:00']`



---



#### Column Profile: `Booking ID`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `10,350,132 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `148,767`
- **Duplicate Values:** `1,233`
- **Duplicate Percentage:** `0.82%`

##### Sample Values
`['"CNR5884300"', '"CNR1326809"', '"CNR8494506"', '"CNR8906825"', '"CNR1950162"']`



---



#### Column Profile: `Booking Status`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `10,368,132 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `5`
- **Duplicate Values:** `149,995`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['No Driver Found', 'Incomplete', 'Completed', 'Cancelled by Driver', 'Cancelled by Customer']`


#####
All Unique Values:
`['No Driver Found', 'Incomplete', 'Completed', 'Cancelled by Driver', 'Cancelled by Customer']`


---



#### Column Profile: `Customer ID`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `10,350,132 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `148,788`
- **Duplicate Values:** `1,212`
- **Duplicate Percentage:** `0.81%`

##### Sample Values
`['"CID1982111"', '"CID4604802"', '"CID9202816"', '"CID2610914"', '"CID9933542"']`



---



#### Column Profile: `Vehicle Type`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `9,535,017 bytes`
- **Null Count:** `0`
- **Null Percentage:** `0.0%`
- **Unique Values:** `7`
- **Duplicate Values:** `149,993`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike']`


#####
All Unique Values:
`['eBike', 'Go Sedan', 'Auto', 'Premier Sedan', 'Bike', 'Go Mini', 'Uber XL']`


---



#### Column Profile: `Cancelled Rides by Customer`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `139,500`
- **Null Percentage:** `93.0%`
- **Unique Values:** `1`
- **Duplicate Values:** `149,998`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`[np.float64(1.0)]`


#####
All Unique Values:
`[np.float64(1.0)]`


---



#### Column Profile: `Reason for cancelling by Customer`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `5,301,498 bytes`
- **Null Count:** `139,500`
- **Null Percentage:** `93.0%`
- **Unique Values:** `5`
- **Duplicate Values:** `149,994`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['Driver is not moving towards pickup location', 'Driver asked to cancel', 'AC is not working', 'Change of plans', 'Wrong Address']`


#####
All Unique Values:
`['Driver is not moving towards pickup location', 'Driver asked to cancel', 'AC is not working', 'Change of plans', 'Wrong Address']`


---



#### Column Profile: `Cancelled Rides by Driver`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `123,000`
- **Null Percentage:** `82.0%`
- **Unique Values:** `1`
- **Duplicate Values:** `149,998`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`[np.float64(1.0)]`


#####
All Unique Values:
`[np.float64(1.0)]`


---



#### Column Profile: `Driver Cancellation Reason`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `6,257,140 bytes`
- **Null Count:** `123,000`
- **Null Percentage:** `82.0%`
- **Unique Values:** `4`
- **Duplicate Values:** `149,995`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['Personal & Car related issues', 'Customer related issue', 'More than permitted people in there', 'The customer was coughing/sick']`


#####
All Unique Values:
`['Personal & Car related issues', 'Customer related issue', 'More than permitted people in there', 'The customer was coughing/sick']`


---



#### Column Profile: `Incomplete Rides`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `141,000`
- **Null Percentage:** `94.0%`
- **Unique Values:** `1`
- **Duplicate Values:** `149,998`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`[np.float64(1.0)]`


#####
All Unique Values:
`[np.float64(1.0)]`


---



#### Column Profile: `Incomplete Rides Reason`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `5,154,364 bytes`
- **Null Count:** `141,000`
- **Null Percentage:** `94.0%`
- **Unique Values:** `3`
- **Duplicate Values:** `149,996`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['Vehicle Breakdown', 'Other Issue', 'Customer Demand']`


#####
All Unique Values:
`['Vehicle Breakdown', 'Other Issue', 'Customer Demand']`


---



#### Column Profile: `Booking Value`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `48,000`
- **Null Percentage:** `32.0%`
- **Unique Values:** `2,566`
- **Duplicate Values:** `147,433`
- **Duplicate Percentage:** `98.29%`

##### Sample Values
`[np.float64(237.0), np.float64(627.0), np.float64(416.0), np.float64(737.0), np.float64(316.0)]`



---



#### Column Profile: `Ride Distance`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `48,000`
- **Null Percentage:** `32.0%`
- **Unique Values:** `4,901`
- **Duplicate Values:** `145,098`
- **Duplicate Percentage:** `96.73%`

##### Sample Values
`[np.float64(5.73), np.float64(13.58), np.float64(34.02), np.float64(48.21), np.float64(4.85)]`



---



#### Column Profile: `Driver Ratings`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `57,000`
- **Null Percentage:** `38.0%`
- **Unique Values:** `21`
- **Duplicate Values:** `149,978`
- **Duplicate Percentage:** `99.99%`

##### Sample Values
`[np.float64(4.9), np.float64(4.6), np.float64(4.1), np.float64(4.0), np.float64(4.4)]`


#####
All Unique Values:
`[np.float64(4.9), np.float64(4.6), np.float64(4.1), np.float64(4.0), np.float64(4.4), np.float64(4.2), np.float64(4.7), np.float64(3.8), np.float64(5.0), np.float64(3.7), np.float64(3.1), np.float64(4.5), np.float64(3.9), np.float64(4.3), np.float64(3.3), np.float64(3.2), np.float64(4.8), np.float64(3.6), np.float64(3.5), np.float64(3.4), np.float64(3.0)]`


---



#### Column Profile: `Customer Rating`

##### Basic Info
- **Data Type:** `float64`
- **Total Rows:** `150,000`
- **Memory Usage:** `1,200,132 bytes`
- **Null Count:** `57,000`
- **Null Percentage:** `38.0%`
- **Unique Values:** `21`
- **Duplicate Values:** `149,978`
- **Duplicate Percentage:** `99.99%`

##### Sample Values
`[np.float64(4.9), np.float64(5.0), np.float64(4.3), np.float64(4.6), np.float64(4.1)]`


#####
All Unique Values:
`[np.float64(4.9), np.float64(5.0), np.float64(4.3), np.float64(4.6), np.float64(4.1), np.float64(4.2), np.float64(4.7), np.float64(4.4), np.float64(3.6), np.float64(4.5), np.float64(3.3), np.float64(3.8), np.float64(3.7), np.float64(4.8), np.float64(3.9), np.float64(3.4), np.float64(3.2), np.float64(3.1), np.float64(4.0), np.float64(3.0), np.float64(3.5)]`


---



#### Column Profile: `Payment Method`

##### Basic Info
- **Data Type:** `object`
- **Total Rows:** `150,000`
- **Memory Usage:** `7,919,052 bytes`
- **Null Count:** `48,000`
- **Null Percentage:** `32.0%`
- **Unique Values:** `5`
- **Duplicate Values:** `149,994`
- **Duplicate Percentage:** `100.0%`

##### Sample Values
`['UPI', 'Debit Card', 'Cash', 'Uber Wallet', 'Credit Card']`


#####
All Unique Values:
`['UPI', 'Debit Card', 'Cash', 'Uber Wallet', 'Credit Card']`


---

### Explanation

Using the gathered information, we can deduct the following information about the fields:

- Time and Date can be combined later to create a timestamp.
- Almost all records are for unqiue customers.
- The Booking ID has duplications. This needs to be investigated.
- Some datatypes are categorical.
- Because the original file is a `csv` file, all the data are either `str`, `int` or `float`.

## Investigation for [Booking ID]

In [8]:
total_rows = len(df)
unique_ids = df['Booking ID'].nunique()
duplicate_ids = df['Booking ID'].duplicated().sum()

print("Total rows:", total_rows)
print("Unique Booking IDs:", unique_ids)
print("Duplicate rows (ID level):", duplicate_ids)

Total rows: 150000
Unique Booking IDs: 148767
Duplicate rows (ID level): 1233

In [12]:
dup_id_counts = (
    df['Booking ID'].value_counts().loc[lambda x: x > 1]
)

print("Number of duplicated IDs:", len(dup_id_counts))
dup_id_counts.head()

Number of duplicated IDs: 1224

Booking ID
"CNR6337479"    3
"CNR7199036"    3
"CNR3648267"    3
"CNR2726142"    3
"CNR5292943"    3
Name: count, dtype: int64

In [15]:
problem_id = dup_id_counts.index[0]
df[df['Booking ID'] == problem_id]

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
114477,10/25/2024,12:09:29,"""CNR6337479""",Completed,"""CID6870480""",eBike,NaN,NaN,NaN,NaN,NaN,NaN,635.0,9.30,3.8,4.2,UPI
134198,11/25/2024,21:58:13,"""CNR6337479""",Completed,"""CID4744805""",Auto,NaN,NaN,NaN,NaN,NaN,NaN,423.0,24.84,4.5,4.9,UPI
135803,1/28/2024,14:19:48,"""CNR6337479""",Completed,"""CID5396601""",Go Sedan,NaN,NaN,NaN,NaN,NaN,NaN,396.0,36.60,4.1,4.5,UPI

#### Result
Apparently, there is a problem with the booking system as there is no relation between the the records with duplicate Booking ID. Later, in the data refining we should think about a solution.
-  One solution could be to check whether the combination of BookingID and CustomerID are unique or no. If yes, this can be used as a Primary Key.


## Logical Relation Between Fields

#### Booking ID

* Should represent the **primary key at booking-level grain**
* If duplicated → Need to be fiexed later.

#### Customer ID

* One-to-many relationship with Booking ID
* A customer can create multiple bookings (but not many did lol)
* Should never change within the same Booking ID

#### Date + Time

* Together define the **request timestamp**
* If Booking ID appears multiple times with different Time → dataset is tracking state transitions
* If Time changes but Booking ID same → this is likely **status evolution**, not duplicate booking

#### Booking Status

* All cancellation and rating fields depend on this column
* 
#### Cancelled Rides by Customer | Reason for cancelling by Customer

Logical rule:

* If Cancelled Rides by Customer > 0
  → Booking Status must be "Cancelled"
  → Reason must NOT be null

If:

* Status ≠ Cancelled
* but cancellation fields are populated
  → Data inconsistency

#### Cancelled Rides by Driver | Driver Cancellation Reason

Same dependency rule:

* If Cancelled Rides by Driver > 0
  → Status = Cancelled
  → Driver Cancellation Reason must exist

Important:
Only one side should cancel per booking.

If both customer and driver cancellation > 0 → data integrity issue.

#### Incomplete Rides | Incomplete Rides Reason

Logical relation:

* If Incomplete Rides > 0
  → Status = Incomplete
  → No Customer Rating should exist
  → Booking Value likely = 0 or partial

#### Completion Logic

If Booking Status = Completed:

Then:

* Ride Distance > 0
* Booking Value > 0
* Driver Ratings not null (but could be)
* Customer Rating not null (but could be)
* No cancellation fields populated

If any of these missing → incomplete completion data.

#### Booking Value

Logically depends on:

* Ride Distance
* Vehicle Type
* Possibly surge pricing (not shown here)

If:

* Ride Distance = 0
* Booking Value > 0
  → anomaly

#### Vehicle Type

Logical behavior:

* Impacts Booking Value
* Impacts Ride Distance pricing
* Does NOT change within same Booking ID

If duplicated Booking ID has different Vehicle Type → structural issue (which has)

#### Customer Rating | Driver Ratings

Logical rule:

* Only exist if ride completed
* Should probably be null if:

  * Cancelled
  * Incomplete

#### Payment Method

Logical behavior:

* Should only exist if ride completed
* Should be null for cancelled rides

If payment method exists but Booking Value = 0 → anomaly