In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)
df = pd.read_csv("../data/Database.csv")
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,3/23/2024,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11/29/2024,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,NaN,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,8/23/2024,8:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,NaN,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,10/21/2024,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,NaN,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,9/16/2024,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,NaN,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

## Dataset Size and Explanation
The dataset is of the following size:
- 17 Fields (Columns/Features)
- 150,000 Records (Instances, Samples)

In [3]:
df.shape

(150000, 17)

In [4]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 17 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Cancelled Rides by Customer        10500 non-null   float64
 7   Reason for cancelling by Customer  10500 non-null   object
 8   Cancelled Rides by Driver          27000 non-null   float64
 9   Driver Cancellation Reason         27000 non-null   object
 10  Incomplete Rides                   9000 non-null    float64
 11  Incomplete Rides Reason            9000 non-null    object
 12  Booking Value                      102000 non-null  float64
 13  Ride Distance                      102000 non-null  float64
 14  Driver Ratings                     93000 non-null   float64
 15  Customer Rating                    93000 non-null   float64
 16  Payment Method                     102000 non-null  object
dtypes: float64(7), object(10)
memory usage: 88.9 MB


### Explanation

Based on the output of the `info()` function, we can conclude the following:

* The dataset occupies approximately **90 MB** of memory.
* It contains **Uber car booking transaction records**.
* Several columns include **null (missing) values**.
* This dataset enables various analyses to better understand the state and performance of **car bookings in 2024**, including trends, cancellations, ride completion rates, revenue patterns, and customer/driver behavior.

### Field-by-Field Analysis

In [5]:
df.dtypes

Date                                  object
Time                                  object
Booking ID                            object
Booking Status                        object
Customer ID                           object
Vehicle Type                          object
Cancelled Rides by Customer          float64
Reason for cancelling by Customer     object
Cancelled Rides by Driver            float64
Driver Cancellation Reason            object
Incomplete Rides                     float64
Incomplete Rides Reason               object
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                        object
dtype: object

In [13]:
nulls = df.isnull().sum().sort_values(ascending=False)

In [19]:
print("Total Null Values")
nulls

Total Null Values

Incomplete Rides                     141000
Incomplete Rides Reason              141000
Reason for cancelling by Customer    139500
Cancelled Rides by Customer          139500
Driver Cancellation Reason           123000
Cancelled Rides by Driver            123000
Driver Ratings                        57000
Customer Rating                       57000
Ride Distance                         48000
Booking Value                         48000
Payment Method                        48000
Date                                      0
Time                                      0
Vehicle Type                              0
Booking ID                                0
Booking Status                            0
Customer ID                               0
TimeStamp                                 0
dtype: int64

In [18]:
null_pct = (df.isnull().mean() * 100).round(2)
print("Percentage of Nulls")
null_pct.sort_values(ascending=False)

Percentage of Nulls

Incomplete Rides                     94.0
Incomplete Rides Reason              94.0
Reason for cancelling by Customer    93.0
Cancelled Rides by Customer          93.0
Driver Cancellation Reason           82.0
Cancelled Rides by Driver            82.0
Driver Ratings                       38.0
Customer Rating                      38.0
Ride Distance                        32.0
Booking Value                        32.0
Payment Method                       32.0
Date                                  0.0
Time                                  0.0
Vehicle Type                          0.0
Booking ID                            0.0
Booking Status                        0.0
Customer ID                           0.0
TimeStamp                             0.0
dtype: float64

In [20]:
categorical_cols = [
    "Booking Status",
    "Vehicle Type",
    "Reason for cancelling by Customer",
    "Driver Cancellation Reason",
    "Incomplete Rides Reason",
    "Payment Method"
]

for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts(dropna=False))

Booking Status
Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

Vehicle Type
Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

Reason for cancelling by Customer
Reason for cancelling by Customer
NaN                                             139500
Wrong Address                                     2362
Change of plans                                   2353
Driver is not moving towards pickup location      2335
Driver asked to cancel                            2295
AC is not working                                 1155
Name: count, dtype: int64

Driver Cancellation Reason
Driver Cancellation Reason
NaN                                    123000
Customer related issue                   6837
The customer was coughing/sick           6751
Personal & Car related issues            6726
More than permitted people in there      6686
Name: count, dtype: int64

Incomplete Rides Reason
Incomplete Rides Reason
NaN                  141000
Customer Demand        3040
Vehicle Breakdown      3012
Other Issue            2948
Name: count, dtype: int64

Payment Method
Payment Method
NaN            48000
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

In [23]:
numeric_cols = [
    "Booking Value",
    "Ride Distance",
    "Driver Ratings",
    "Customer Rating"
]

df[numeric_cols].describe()

       Booking Value  Ride Distance  Driver Ratings  Customer Rating
count  102000.000000  102000.000000    93000.000000     93000.000000
mean      508.295912      24.637012        4.230992         4.404584
std       395.805774      14.002138        0.436871         0.437819
min        50.000000       1.000000        3.000000         3.000000
25%       234.000000      12.460000        4.100000         4.200000
50%       414.000000      23.720000        4.300000         4.500000
75%       689.000000      36.820000        4.600000         4.800000
max      4277.000000      50.000000        5.000000         5.000000

In [28]:
## is BookingId a UID?
print(df['Booking ID'].nunique())

148767

The dataset has the following set of fields: 
> Note that each transaction referes to the act of trying to order a ride from uber.
- Date: Shows the date which the transaction happens. It is of 'str' datatype originaly but can be translated to a timestamp. This field dosn't have any null values.
- Time: The time in which the transaction happend. It is of type 'str' and has no null values.
- Booking ID: A unique i
- Booking Status                    
- Customer ID                       
- Vehicle Type                      
- Cancelled Rides by Customer       
- Reason for cancelling by Customer 
- Cancelled Rides by Driver         
- Driver Cancellation Reason        
- Incomplete Rides                  
- Incomplete Rides Reason           
- Booking Value                     
- Ride Distance                     
- Driver Ratings                    
- Customer Rating                   
- Payment Method